// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4wuR6djweT7vAchr7evKHM
// Component: 4Tj1PFl3Qc
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: 4wuR6djweT7vAchr7evKHM/projectcss
import sty from "./PlasmicRecommandationLogiciel.module.css"; // plasmic-import: 4Tj1PFl3Qc/css

export const PlasmicRecommandationLogiciel__VariantProps = new Array();

export const PlasmicRecommandationLogiciel__ArgProps = new Array();

function PlasmicRecommandationLogiciel__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRecommandationLogiciel__ArgProps,
      internalVariantPropNames: PlasmicRecommandationLogiciel__VariantProps
    });

    return PlasmicRecommandationLogiciel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRecommandationLogiciel";
  } else {
    func.displayName = `PlasmicRecommandationLogiciel.${nodeName}`;
  }
  return func;
}

export const PlasmicRecommandationLogiciel = Object.assign(
  // Top-level PlasmicRecommandationLogiciel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicRecommandationLogiciel
    internalVariantProps: PlasmicRecommandationLogiciel__VariantProps,
    internalArgProps: PlasmicRecommandationLogiciel__ArgProps
  }
);

export default PlasmicRecommandationLogiciel;
/* prettier-ignore-end */
