// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4wuR6djweT7vAchr7evKHM
// Component: gMJdaty2uR
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Btn from "../../Btn"; // plasmic-import: gIUt2Bx9WL/component
import { useScreenVariants as useScreenVariantsniCroJ2MX1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Ni-CroJ2mX1/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 4wuR6djweT7vAchr7evKHM/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: gMJdaty2uR/css

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsniCroJ2MX1()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            className={classNames(projectcss.all, sty.section1)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"column1"}
              data-plasmic-override={overrides.column1}
              hasGap={true}
              className={classNames(projectcss.all, sty.column1)}
            >
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Une expertise numérique dédiée aux entreprises de services"
                  : "Une expertise numérique dédiée aux entreprises de services"}
              </h1>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xyoZo
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit. \n\nQuisque malesuada hendrerit elit, ut placerat neque tempus non. Phasellus bibendum tortor est."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit, ut placerat neque tempus non. Phasellus bibendum tortor est."}
              </div>

              <Btn
                className={classNames("__wab_instance", sty.btn__kZn96)}
                type={"primary"}
              >
                {"En savoir plus"}
              </Btn>
            </p.Stack>

            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
            ) ? (
              <div
                data-plasmic-name={"column2"}
                data-plasmic-override={overrides.column2}
                className={classNames(projectcss.all, sty.column2)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__np82R)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/image.png",
                    fullWidth: 1956,
                    fullHeight: 1434,
                    aspectRatio: undefined
                  }}
                />
              </div>
            ) : null}
          </div>

          <div
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            className={classNames(projectcss.all, sty.section2)}
          >
            <div
              data-plasmic-name={"column4"}
              data-plasmic-override={overrides.column4}
              className={classNames(projectcss.all, sty.column4)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__htHu3)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blank_project/images/image2.png",
                  fullWidth: 1608,
                  fullHeight: 1060,
                  aspectRatio: undefined
                }}
              />
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"column3"}
              data-plasmic-override={overrides.column3}
              hasGap={true}
              className={classNames(projectcss.all, sty.column3)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__iLkWy
                )}
              >
                {"La meilleure expérience de transformation numérique"}
              </h2>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jMPxg
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit, ut placerat neque tempus non. Phasellus bibendum tortor est."
                }
              </div>

              <Btn
                className={classNames("__wab_instance", sty.btn___5Ppy9)}
                type={"secondary"}
              >
                {"Découvrir nos services"}
              </Btn>
            </p.Stack>
          </div>

          <div
            data-plasmic-name={"section3"}
            data-plasmic-override={overrides.section3}
            className={classNames(projectcss.all, sty.section3)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"column6"}
              data-plasmic-override={overrides.column6}
              hasGap={true}
              className={classNames(projectcss.all, sty.column6)}
            >
              {(
                hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
              ) ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__z7Xjc)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__yyAfJ
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Êtes-vous en pénurie de main d'oeuvre ?"
                      : "Etes-vous en pénurie de main d'oeuvre ?"}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ydF5T
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit, ut placerat neque tempus non. Phasellus bibendum tortor est."
                    }
                  </div>

                  <Btn
                    className={classNames("__wab_instance", sty.btn__skHxF)}
                    type={"primary"}
                  >
                    {"Demander une démo"}
                  </Btn>
                </p.Stack>
              ) : null}
            </p.Stack>

            <div
              data-plasmic-name={"column5"}
              data-plasmic-override={overrides.column5}
              className={classNames(projectcss.all, sty.column5)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__htIim)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blank_project/images/image3.png",
                  fullWidth: 1732,
                  fullHeight: 2834,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.columns___22BJp)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.column__foc4B)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ypwWt
                )}
              >
                {"Soyez indépendant de vos technologies"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rSxR
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit. \n\nQuisque malesuada hendrerit elit, ut placerat neque tempus non. Phasellus bibendum tortor est."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit, ut placerat neque tempus non. Phasellus bibendum tortor est."}
              </div>

              <Btn
                className={classNames("__wab_instance", sty.btn__nhHb)}
                type={"tertiary"}
              >
                {"Demander une démo"}
              </Btn>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.column__ie1Kl)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___99Cjx)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/tooly_services/images/image4.png",
                  fullWidth: 1776,
                  fullHeight: 2128,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.columns__mg6Uq)}>
            <div className={classNames(projectcss.all, sty.column__hlShc)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__elEDr)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"600px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/tooly_services/images/image5.png",
                  fullWidth: 1254,
                  fullHeight: 1046,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__lpb3J)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xkiKa
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac magna id mi tristique tincidunt sit amet at odio. Praesent vel consequat mauris. \n\nNulla placerat sapien non faucibus hendrerit. Pellentesque in fringilla tellus. Aliquam id elit at erat sollicitudin iaculis. \n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis magna lectus. Suspendisse imperdiet justo vel sem accumsan, sed dapibus tellus consectetur."
                }
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.columns__vvglt)}>
            <div className={classNames(projectcss.all, sty.column__sn9Kl)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__z8ZqS)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"400px"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/tooly_services/images/image6.png",
                  fullWidth: 814,
                  fullHeight: 1006,
                  aspectRatio: undefined
                }}
              />
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.column___9HpQq)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0KV2D
                )}
              >
                {"Pourquoi nous choisir"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vFujV
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit. \n\nQuisque malesuada hendrerit elit, ut placerat neque tempus non. Phasellus bibendum tortor est."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit, ut placerat neque tempus non. Phasellus bibendum tortor est."}
              </div>

              <Btn
                className={classNames("__wab_instance", sty.btn__nab2T)}
                type={"tertiary"}
              >
                {"Demander une démo"}
              </Btn>
            </p.Stack>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__amEs7)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rRcrj
              )}
            >
              {"Faire affaire avec Tooly a quelques avantages"}
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__wmaUi)}>
            <div className={classNames(projectcss.all, sty.columns__pxT)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__xOmVn)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__lriGu)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__kqkXj)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"75%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tooly_services/images/image7.png",
                      fullWidth: 439,
                      fullHeight: 445,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1UMxv
                  )}
                >
                  {"Automatisation des tâches manuelles"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mlWf
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit"
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___53Ax9)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__uiYg5)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__frHbW)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tooly_services/images/saly24Png.png",
                      fullWidth: 283,
                      fullHeight: 282,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vae5A
                  )}
                >
                  {"Bien-être de vos employés"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xvsWz
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit"
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__bfAfD)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__sl84N)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__uloY1)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tooly_services/images/saly43Png.png",
                      fullWidth: 681,
                      fullHeight: 720,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xhxB3
                  )}
                >
                  {"Forte croissance"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z8ORp
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit"
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__h9U31)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__eyq3R)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___2M1Iq)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tooly_services/images/saly241Png.png",
                      fullWidth: 222,
                      fullHeight: 221,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__esqpf
                  )}
                >
                  {"Vous rendre indépendants"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lhpVv
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit"
                  }
                </div>
              </p.Stack>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__fnEsm)}>
            <div className={classNames(projectcss.all, sty.freeBox__brqlc)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aNLl9
                )}
              >
                {"Quelques exemples de processus que l'on maîtrise"}
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox___1ZZg1)}>
              <div className={classNames(projectcss.all, sty.columns__aZyt2)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__rbxeT)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cot7B)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pzSum)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/tooly_services/images/frame2791Png.png",
                        fullWidth: 440,
                        fullHeight: 441,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sJnv5
                    )}
                  >
                    {"Processus de ventes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6MMfQ
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit"
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column___4TjZv)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nC7PI)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__eE38A)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/tooly_services/images/frame2792Png.png",
                        fullWidth: 441,
                        fullHeight: 441,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mWy8C
                    )}
                  >
                    {"Processus de fidélisation de la clientèle"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fVSu
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit"
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column___5Id5C)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__aaNeG)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hgh38)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/tooly_services/images/frame2794Png.png",
                        fullWidth: 440,
                        fullHeight: 441,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xFomn
                    )}
                  >
                    {"Processus de gestion des ressources humaines"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___778KI
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit"
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__b3MEq)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__goNna)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tKc2V)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/tooly_services/images/frame2795Png.png",
                        fullWidth: 441,
                        fullHeight: 441,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1Xz2
                    )}
                  >
                    {"Processus de logistique"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ctAw2
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada hendrerit elit"
                    }
                  </div>
                </p.Stack>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__zdfCa)} />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "section1",
    "column1",
    "h1",
    "column2",
    "section2",
    "column4",
    "column3",
    "section3",
    "column6",
    "column5"
  ],

  section1: ["section1", "column1", "h1", "column2"],
  column1: ["column1", "h1"],
  h1: ["h1"],
  column2: ["column2"],
  section2: ["section2", "column4", "column3"],
  column4: ["column4"],
  column3: ["column3"],
  section3: ["section3", "column6", "column5"],
  column6: ["column6"],
  column5: ["column5"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section1: makeNodeComponent("section1"),
    column1: makeNodeComponent("column1"),
    h1: makeNodeComponent("h1"),
    column2: makeNodeComponent("column2"),
    section2: makeNodeComponent("section2"),
    column4: makeNodeComponent("column4"),
    column3: makeNodeComponent("column3"),
    section3: makeNodeComponent("section3"),
    column6: makeNodeComponent("column6"),
    column5: makeNodeComponent("column5"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
